// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"624","screenHeight":"816","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"UR65_SmartPhoneUI","status":true,"description":"スマホ用UI  ver 1.0.0\nUIのサイズをスマートフォン向けに最適化します。","parameters":{"タイトル":"1","メニュー":"1","アイテム":"1","スキル":"1","装備":"1","オプション":"1","ゲーム終了":"1","戦闘":"1","ショップ":"1","イベント関係":"1","アイコン位置修正":"1"}},
{"name":"WindowsPosi","status":true,"description":"","parameters":{}},
{"name":"FTKR_PopupSpriteMessage","status":true,"description":"v1.2.5 任意のメッセージを画面上にポップアップ表示するプラグイン","parameters":{"Max Popup Messages":"10","Popup Message Status":"[\"{\\\"fontFace\\\":\\\"\\\",\\\"fontSize\\\":\\\"28\\\",\\\"color\\\":\\\"[\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\"]\\\",\\\"italic\\\":\\\"false\\\",\\\"outlineColor\\\":\\\"\\\",\\\"popupHeight\\\":\\\"0\\\",\\\"offsetWait\\\":\\\"0\\\",\\\"opacity\\\":\\\"255\\\"}\",\"{\\\"fontFace\\\":\\\"\\\",\\\"fontSize\\\":\\\"28\\\",\\\"color\\\":\\\"[\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\"]\\\",\\\"italic\\\":\\\"false\\\",\\\"outlineColor\\\":\\\"15\\\",\\\"popupHeight\\\":\\\"0\\\",\\\"offsetWait\\\":\\\"0\\\",\\\"opacity\\\":\\\"255\\\"}\",\"{\\\"fontFace\\\":\\\"\\\",\\\"fontSize\\\":\\\"22\\\",\\\"color\\\":\\\"[\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\",\\\\\\\"0\\\\\\\"]\\\",\\\"italic\\\":\\\"false\\\",\\\"outlineColor\\\":\\\"15\\\",\\\"popupHeight\\\":\\\"0\\\",\\\"offsetWait\\\":\\\"0\\\",\\\"opacity\\\":\\\"255\\\"}\"]","Repop Message After Menu":"false"}},
{"name":"PNDK_FloatingPointVariables","status":true,"description":"変数に小数を代入できるようにします。","parameters":{"numDigits":"0"}},
{"name":"MPP_ChoiceEX","status":true,"description":"【ver.3.6】選択肢の機能拡張","parameters":{"maxPageRow":"6","=== Command ===":"","Plugin Commands":"{\"ChoicePos\":\"ChoicePos\",\"ChoiceVariableId\":\"ChoiceVariableId\",\"ChoiceRect\":\"ChoiceRect\"}","Event Comment":"{\"ChoiceHelp\":\"選択肢ヘルプ\"}"}}
];
